fixed issue with running in dev from node modules, will now use serve…
greenpress/cli-service-pm2 pull request #12
Opened 2020-10-08 11:42 UTC by drorrose

…r.js like in prod

2020-10-08 12:15 UTC, davidmeirlevy requested changes

2020-10-08 12:15 UTC, davidmeirlevy commented on config/base-config.js
> +      script: process.env.ADMIN_SERVICE_SCRIPT ||  (IS_PROD || isAdminRunningFromNodeModules ? 'server.js' : 'npm run serve')
it shouldn’t be on the `base-config.js` but on the `config.js` file.
the base-config doesn't include the user's configuration.

2020-10-08 22:16 UTC, drorrose commented on config/base-config.js
> +      script: process.env.ADMIN_SERVICE_SCRIPT ||  (IS_PROD || isAdminRunningFromNodeModules ? 'server.js' : 'npm run serve')
Done, check the changes out (I tested them on both env variable and regular dev run but didn't manage to test it on config file)

2020-10-09 07:01 UTC, davidmeirlevy approved these changes

2020-10-09 07:01 UTC, merged