added node-saas rebuild for admin and blog front in case working from…
greenpress/cli-service-pm2 pull request #17
Opened 2020-11-17 18:32 UTC by drorrose

… dev folder (for mac and windows)

2020-11-17 19:24 UTC, davidmeirlevy requested changes

2020-11-17 19:24 UTC, davidmeirlevy commented on config/index.js
> +	if (el.cwd.includes('node_modules')) {
this line should only apply to the admin panel

2020-11-21 11:45 UTC, drorrose commented on config/index.js
> +	if (el.cwd.includes('node_modules')) {
Done

2020-11-21 11:50 UTC, davidmeirlevy approved these changes

2020-11-21 12:37 UTC, merged